"""accounts, ledger, jobs and governance

The initial schema: component 15 §7's accounts and billing tables, master §4's
jobs/job_events/artifacts/ledger, component 05 §7's proposals and moderation,
component 09 §7's private-tree listing rows.

Two things here are not autogenerated and must not be dropped by a later
autogenerate diff:

* the ``ledger_append_only`` trigger — Alembic does not see triggers, so it is
  written by hand and shares its SQL with ``explorer_api.models``;
* the three ``plans`` rows — ``users.plan_id`` defaults to ``'free'`` and is a
  foreign key, so a database with no plans cannot hold a user. The numbers are
  component 15 §5; ``api/plans.py`` (Task 5) stays the authority and a drift
  test there compares the two.

Revision ID: 23eeb106db35
Revises:
Create Date: 2026-08-31 07:07:38.631911
"""
from __future__ import annotations

from collections.abc import Sequence

from decimal import Decimal

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from explorer_api.models import LEDGER_APPEND_ONLY_DROP_SQL, LEDGER_APPEND_ONLY_SQL

revision: str = '23eeb106db35'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('included_credit_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('quotas', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('stripe_price_id', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("id IN ('free', 'starter', 'pro')", name=op.f('ck_plans_plans_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_table('prices',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('unit_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('input', 'output', 'embedding', 'storage_mb_month')", name=op.f('ck_prices_prices_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices')),
    sa.UniqueConstraint('model', 'kind', 'effective_from', name='uq_prices_model_kind_effective_from')
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_events'))
    )
    op.create_index(op.f('ix_stripe_events_type'), 'stripe_events', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.String(length=16), server_default='free', nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_users_plan_id_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('max_usd_day', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scopes <@ ARRAY['read','run','publish']::text[]", name=op.f('ck_api_keys_ck_api_keys_scopes')),
    sa.CheckConstraint('array_length(scopes, 1) >= 1', name=op.f('ck_api_keys_ck_api_keys_scopes_nonempty')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=True)
    op.create_table('auth_oauth',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('github', 'google')", name=op.f('ck_auth_oauth_auth_oauth_provider')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_oauth_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_oauth')),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_auth_oauth_provider_provider_account_id')
    )
    op.create_table('auth_passkeys',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('transports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aaguid', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_passkeys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_passkeys')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_auth_passkeys_credential_id'))
    )
    op.create_table('credits',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_credits'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('input_ref', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='created', nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('estimate_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('worker', sa.Text(), nullable=True),
    sa.Column('lease_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_tokens', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('artifact_ref', sa.Text(), nullable=True),
    sa.Column('log_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('lint', 'optimize', 'notes', 'topical', 'abstract', 'pack', 'deepen', 'research', 'family', 'resolve', 'index', 'benchmark', 'probe', 'publish')", name=op.f('ck_jobs_jobs_kind')),
    sa.CheckConstraint("status IN ('created', 'queued', 'running', 'held', 'done', 'failed', 'cancelled')", name=op.f('ck_jobs_jobs_status')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_jobs_ck_jobs_attempts_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_status_lease_expires', 'jobs', ['status', 'lease_expires'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_index('ix_jobs_user_id_input_hash', 'jobs', ['user_id', 'input_hash'], unique=False)
    op.create_table('moderation',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_kind', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('assignee_user_id', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('findings_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'approved', 'rejected')", name=op.f('ck_moderation_moderation_state')),
    sa.CheckConstraint("subject_kind IN ('proposal', 'contribution', 'artifact')", name=op.f('ck_moderation_moderation_subject_kind')),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_moderation_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_moderation_decided_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation')),
    sa.UniqueConstraint('subject_kind', 'subject_id', name='uq_moderation_subject_kind_subject_id')
    )
    op.create_index('ix_moderation_state_created_at', 'moderation', ['state', 'created_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.String(length=16), nullable=False),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('incomplete', 'incomplete_expired', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'paused')", name=op.f('ck_subscriptions_subscriptions_state')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('uq_subscriptions_stripe_subscription_id'))
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('trees',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), server_default='me', nullable=False),
    sa.Column('forked_from_sha', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trees')),
    sa.UniqueConstraint('user_id', 'slug', name='uq_trees_user_id_slug')
    )
    op.create_index(op.f('ix_trees_user_id'), 'trees', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=8), server_default='public', nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('manifest_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('lint_summary_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(visibility = 'public' AND owner_user_id IS NULL) OR (visibility = 'private' AND owner_user_id IS NOT NULL)", name=op.f('ck_artifacts_ck_artifacts_private_has_owner')),
    sa.CheckConstraint("kind IN ('index', 'family', 'full', 'small', 'facts', 'split-root', 'vocabulary', 'concept-pack')", name=op.f('ck_artifacts_artifacts_kind')),
    sa.CheckConstraint("visibility IN ('public', 'private')", name=op.f('ck_artifacts_artifacts_visibility')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_artifacts_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_artifacts_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_owner_user_id'), 'artifacts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_artifacts_slug'), 'artifacts', ['slug'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("kind IN ('stage', 'iteration', 'findings', 'tokens', 'log')", name=op.f('ck_job_events_job_events_kind')),
    sa.CheckConstraint('seq >= 1', name=op.f('ck_job_events_ck_job_events_seq_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events')),
    sa.UniqueConstraint('job_id', 'seq', name='uq_job_events_job_id_seq')
    )
    op.create_table('ledger',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('call_id', sa.Text(), nullable=True),
    sa.Column('component', sa.String(length=2), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('units', sa.BIGINT(), nullable=False),
    sa.Column('unit_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component IN ('01', '02', '05', '06', '07', '08', '13', '16', '17')", name=op.f('ck_ledger_ledger_component')),
    sa.CheckConstraint("kind IN ('input', 'output', 'embedding', 'storage_mb_month')", name=op.f('ck_ledger_ledger_kind')),
    sa.CheckConstraint('units >= 0', name=op.f('ck_ledger_ck_ledger_units_non_negative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_ledger_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger'))
    )
    op.create_index(op.f('ix_ledger_job_id'), 'ledger', ['job_id'], unique=False)
    op.create_index(op.f('ix_ledger_user_id'), 'ledger', ['user_id'], unique=False)
    op.create_index('ix_ledger_user_id_at', 'ledger', ['user_id', 'at'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('tree_id', sa.Text(), nullable=True),
    sa.Column('tree_sha', sa.Text(), nullable=False),
    sa.Column('patch_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='proposed', nullable=False),
    sa.Column('lint_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('moderator_user_id', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'merged', 'rejected')", name=op.f('ck_proposals_proposals_status')),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], name=op.f('fk_proposals_moderator_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_proposals_tree_id_trees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_proposals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    op.create_index(op.f('ix_proposals_user_id'), 'proposals', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- the ledger is append-only (plan Global Constraints) -----------------
    # Alembic autogenerate does not model triggers; this is hand-written and
    # shares its SQL with explorer_api.models so the two cannot drift.
    for statement in LEDGER_APPEND_ONLY_SQL:
        op.execute(statement)

    # --- the three plans (15 §5) --------------------------------------------
    # `null` in a quota means "no limit". Seeded here because users.plan_id is a
    # foreign key defaulting to 'free': without these rows no account can exist.
    op.bulk_insert(
        sa.table(
            "plans",
            sa.column("id", sa.String),
            sa.column("name", sa.Text),
            sa.column("price_usd", sa.Numeric(12, 6)),
            sa.column("included_credit_usd", sa.Numeric(12, 6)),
            sa.column("quotas", postgresql.JSONB),
            sa.column("sort_order", sa.Integer),
            sa.column("active", sa.Boolean),
        ),
        [
            {
                "id": "free",
                "name": "Free",
                "price_usd": Decimal("0"),
                "included_credit_usd": Decimal("0"),
                "quotas": {
                    "lint_max_bytes": 65536,
                    "lint_per_day": 20,
                    "lint_model_passes": False,
                    "keyword_queries_per_day": 200,
                    "semantic_queries": "demo-only",
                    "indexes": 1,
                    "index_max_units": 20000,
                    "storage_gb": 0.2,
                    "private_trees": 1,
                    "publish": False,
                    "overage": False,
                },
                "sort_order": 0,
                "active": True,
            },
            {
                "id": "starter",
                "name": "Starter",
                "price_usd": Decimal("9"),
                "included_credit_usd": Decimal("10"),
                "quotas": {
                    "lint_max_bytes": None,
                    "lint_per_day": None,
                    "lint_model_passes": True,
                    "keyword_queries_per_day": 5000,
                    "semantic_queries": "credits",
                    "indexes": 5,
                    "index_max_units": None,
                    "storage_gb": 5,
                    "private_trees": 3,
                    "publish": True,
                    "overage": "opt-in",
                },
                "sort_order": 1,
                "active": True,
            },
            {
                "id": "pro",
                "name": "Pro",
                "price_usd": Decimal("39"),
                "included_credit_usd": Decimal("50"),
                "quotas": {
                    "lint_max_bytes": None,
                    "lint_per_day": None,
                    "lint_model_passes": True,
                    "keyword_queries_per_day": 50000,
                    "semantic_queries": "credits",
                    "indexes": 50,
                    "index_max_units": None,
                    "storage_gb": 50,
                    "private_trees": 20,
                    "publish": True,
                    "overage": "opt-in",
                },
                "sort_order": 2,
                "active": True,
            },
        ],
    )


def downgrade() -> None:
    for statement in LEDGER_APPEND_ONLY_DROP_SQL:
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_user_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_ledger_user_id_at', table_name='ledger')
    op.drop_index(op.f('ix_ledger_user_id'), table_name='ledger')
    op.drop_index(op.f('ix_ledger_job_id'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_artifacts_slug'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_user_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_trees_user_id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_moderation_state_created_at', table_name='moderation')
    op.drop_table('moderation')
    op.drop_index('ix_jobs_user_id_input_hash', table_name='jobs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index('ix_jobs_status_lease_expires', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('credits')
    op.drop_table('auth_passkeys')
    op.drop_table('auth_oauth')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index(op.f('ix_stripe_events_type'), table_name='stripe_events')
    op.drop_table('stripe_events')
    op.drop_table('prices')
    op.drop_table('plans')
    # ### end Alembic commands ###
