import json, subprocess
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]


def test_build_emits_index_and_collection_routes():
    subprocess.run(["npm", "run", "build"], cwd=SITE, check=True, capture_output=True)
    dist = SITE / "dist"
    assert (dist / "index.html").is_file()
    assert (dist / "reference" / "attributes" / "index.html").is_file()  # generated by tools/gen_reference.py (Task 3)


def test_collections_declared():
    cfg = (SITE / "src" / "content" / "config.ts").read_text()
    for name in ("reference", "essays", "examples", "blog"):
        assert f"{name}:" in cfg
