# ruff: noqa: E501  -- fixture strings and asserted spans are real site lines; wrapping changes what is tested
import re
import subprocess
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]
COLLECTIONS = ("reference", "essays", "examples", "blog")
HREF_RE = re.compile(r'href="(/[^"#?]*)(?:[#?][^"]*)?"')


def test_build_emits_index_and_collection_routes():
    subprocess.run(["npm", "run", "build"], cwd=SITE, check=True, capture_output=True)
    dist = SITE / "dist"
    assert (dist / "index.html").is_file()
    assert (dist / "reference" / "attributes" / "index.html").is_file()  # generated by tools/gen_reference.py (Task 3)


def test_every_collection_has_a_landing_page():
    """The nav on all 37 pages links `/reference/`, `/essays/`, `/examples/`,
    `/blog/`; each must be a built page listing that collection."""
    dist = SITE / "dist"
    for c in COLLECTIONS:
        page = dist / c / "index.html"
        assert page.is_file(), f"/{c}/ is linked from every page but not built"
        html = page.read_text(encoding="utf-8")
        leaves = [p.parent.name for p in sorted((dist / c).glob("*/index.html"))]
        assert leaves, f"no pages under /{c}/"
        for slug in leaves:
            assert f'href="/{c}/{slug}/"' in html, f"/{c}/ does not list /{c}/{slug}/"


def test_internal_links_resolve():
    """No page links a route the build does not produce."""
    dist = SITE / "dist"
    pages = sorted(dist.rglob("*.html"))
    assert pages, "no built pages under site/dist — run `npm run build` first"
    broken = []
    for p in pages:
        for href in HREF_RE.findall(p.read_text(encoding="utf-8")):
            target = dist / href.lstrip("/")
            if target.is_file() or (target / "index.html").is_file():
                continue
            broken.append(f"{p.relative_to(dist)} -> {href}")
    assert not broken, (
        "pages link routes the build does not produce (fix the link or add the "
        f"route — do not relax this test): {sorted(set(broken))[:10]}")


def test_collections_declared():
    cfg = (SITE / "src" / "content" / "config.ts").read_text()
    for name in COLLECTIONS:
        assert f"{name}:" in cfg
