"""The llms family, rendered from a coverage report.

Five files and a manifest, in the grammars the lint rubric checks and the hub's
own exporter writes — not a second dialect invented here:

``llms.txt``
    Spec v2: a BOM-free H1, a blockquote summary, a generated-by comment, then
    H2 sections of ``- [name](url): description`` link lines. One section per
    topic, in coverage order, so the most substantial subject is first.

``llms-full.txt``
    The **mintlify** grammar, declared in a header comment as the rubric
    requires: per page, ``# Title`` / ``Source: <url>`` / blank / body, pages
    separated by ``---``. It is the corpus's own pages, not a re-rendering of
    the topics — a full file that paraphrased its sources would be a full file
    nobody can check against them.

``llms-small.txt``
    The same index shape, budgeted. Reference-class material first, then the
    deepest topics, cut at the token budget rather than at a page count, and it
    says in its own header where it was cut.

``llms-facts.txt``
    ``- [type] text — url#anchor`` per line, grouped by topic with an HTML
    anchor per section so the index can link into it. Every line carries the
    source that says it; a line that could not carry one is not written.

``manifest.json``
    Bytes and tokens per file, the section list, and the drop counts. H8 in the
    rubric wants exactly one authoritative number per file, and this is where
    the site's twin generator and the serving headers read it from.

The size ladder is the point of the set: the index is small enough to hold in
context, the small file is a budgeted middle, and the full file is the thing you
fetch when you have decided you need it. :func:`build_family` enforces that the
ladder is actually monotonic and says so if the inputs make it impossible.
"""

from __future__ import annotations

import datetime as dt
import json
from collections.abc import Sequence
from dataclasses import dataclass

from .coverage import CoverageReport, Topic
from .ingest import Corpus
from .organize import OutputFile
from .tokens import estimate
from .units import Unit, UnitPool

#: Declared in `llms-full.txt`'s first line, as the rubric's grammar check wants.
FULL_GRAMMAR = "mintlify"

#: Default ceiling for `llms-small.txt`. The rubric's guidance is "≤ ~50k
#: tokens, reference-class first"; component 02 §3 repeats it.
SMALL_TOKEN_BUDGET = 50_000

#: Types that lead `llms-small.txt`: what a reader needs to orient, before
#: anything that is merely true.
REFERENCE_FIRST: tuple[str, ...] = ("definition", "concept", "parameter", "fact",
                                    "actionable", "snippet")

_GENERATOR = "llmsx corpus"


def _summary(report: CoverageReport, subject: str) -> str:
    """The blockquote. States what the family is and how well it covers it.

    Deliberately carries the coverage numbers: a summary that says "a
    comprehensive guide" and a coverage score of 0.11 cannot both be true, and
    the one that is checkable should be the one on the page.
    """
    return (
        f"{report.units} source-anchored knowledge units drawn from {report.sources} "
        f"documents about {subject}, filed under {len(report.topics)} topics. "
        f"Coverage: breadth {report.breadth:.2f}, depth {report.depth:.2f}, "
        f"comprehensiveness {report.comprehensiveness:.2f}. Every line names the "
        f"source it came from."
    )


def _stamp(report: CoverageReport, generated: str) -> str:
    return (f"<!-- generated by {_GENERATOR} · {report.units} units / "
            f"{report.sources} sources · {generated} -->")


def _describe(topic: Topic) -> str:
    """A link line's description: what the topic holds, not an adjective."""
    kinds = ", ".join(
        f"{topic.count(t)} {t}{'s' if topic.count(t) != 1 else ''}"
        for t in ("definition", "fact", "actionable", "snippet")
        if topic.count(t)
    )
    tail = f" ({kinds})" if kinds else ""
    return (f"{len(topic.units)} units from {len(topic.sources)} "
            f"source{'s' if len(topic.sources) != 1 else ''}, depth "
            f"{topic.depth:.2f}{tail}")


def render_index(report: CoverageReport, *, subject: str, generated: str,
                 layout: dict[str, str] | None = None) -> str:
    """``llms.txt`` — spec v2.

    ``layout`` maps a topic slug to the organised markdown file that holds it,
    when the family is shipped beside the topic files. Without it the sections
    link into ``llms-facts.txt``'s anchors, which is what a standalone family
    has to do.
    """
    lines = [f"# {subject}", "", f"> {_summary(report, subject)}", "",
             _stamp(report, generated), ""]
    if not report.topics:
        lines += ["No topics were found in the supplied material.", ""]
        return "\n".join(lines)

    for topic in report.topics:
        target = (layout or {}).get(topic.slug) or f"llms-facts.txt#{topic.slug}"
        lines += [f"## {topic.name}", ""]
        lines.append(f"- [{topic.name}]({target}): {_describe(topic)}")
        for source in topic.sources[:6]:
            said = sum(1 for u in topic.units if u.source == source)
            lines.append(f"- [{source}]({source}): {said} unit{'s' if said != 1 else ''}")
        lines.append("")

    if report.gaps:
        lines += ["## Optional", "",
                  "- [Coverage gaps](llms-facts.txt#gaps): "
                  f"{len(report.gaps)} places this corpus is thin", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_full(corpus: Corpus, *, subject: str, generated: str) -> str:
    """``llms-full.txt`` — the mintlify grammar, declared in line 1."""
    header = [
        f"<!-- llms-full grammar: {FULL_GRAMMAR} — per page: "
        "'# Title' / 'Source: <url>' / blank / body -->",
        f"<!-- {subject} · {len(corpus.pages)} pages · generated {generated} -->",
        "",
    ]
    body: list[str] = []
    for page in corpus.pages:
        body += [f"# {page.title}", f"Source: {page.source}", "", page.body.strip(), "", "---", ""]
    if body:
        body = body[:-2]            # no trailing rule after the last page
    return "\n".join([*header, *body]).rstrip() + "\n"


def _small_units(report: CoverageReport) -> list[Unit]:
    """Reference-class first, then by topic depth. The rubric's ordering."""
    ordered: list[Unit] = []
    for type_ in REFERENCE_FIRST:
        for topic in report.topics:
            ordered.extend(u for u in topic.units if u.type == type_)
    seen: set[str] = set()
    out: list[Unit] = []
    for unit in ordered:
        if unit.key in seen:
            continue
        seen.add(unit.key)
        out.append(unit)
    return out


def render_small(report: CoverageReport, *, subject: str, generated: str,
                 budget: int = SMALL_TOKEN_BUDGET) -> str:
    """``llms-small.txt`` — budgeted, and honest about where it stopped."""
    head = [f"# {subject} — small", "", f"> {_summary(report, subject)}", "",
            _stamp(report, generated), ""]
    used = estimate("\n".join(head))
    body: list[str] = []
    written = 0
    total = 0
    current = ""
    for unit in _small_units(report):
        total += 1
        line = f"- [{unit.type}] {unit.text} — {unit.url}"
        heading = unit.heading or unit.document
        addition = estimate(line) + (estimate(f"## {heading}") + 2 if heading != current else 0)
        if used + addition > budget:
            continue
        if heading != current:
            current = heading
            body += ["", f"## {heading}", ""]
        body.append(line)
        used += addition
        written += 1
    if written < total:
        head.insert(5, f"<!-- budgeted: {written} of {total} reference-class units "
                       f"fit the {budget}-token ceiling -->")
    return "\n".join([*head, *body]).rstrip() + "\n"


def render_facts(report: CoverageReport, *, subject: str, generated: str) -> str:
    """``llms-facts.txt`` — one anchored line per unit, grouped by topic."""
    lines = [f"# {subject} — facts", "", f"> {_summary(report, subject)} "
             "Every line ends in the URL it came from.", "",
             _stamp(report, generated), ""]
    for topic in report.topics:
        lines += [f"## {topic.name}", f'<a id="{topic.slug}"></a>', ""]
        for unit in topic.units:
            text = unit.text.replace("\n", " ").strip() if unit.type != "snippet" else \
                f"`{unit.text.splitlines()[0].strip()}`"
            lines.append(f"- [{unit.type}] {text} — {unit.url}")
        lines.append("")
    if report.gaps:
        lines += ["## Gaps", '<a id="gaps"></a>', ""]
        for gap in report.gaps:
            lines.append(f"- [problem] {gap.topic}: {gap.message} — "
                         f"remedy: {gap.remedy} — {gap.severity}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_vocabulary(report: CoverageReport, pool: UnitPool, *, subject: str,
                      generated: str, limit: int = 400) -> str:
    """``llms-vocabulary.txt`` — the corpus's own terms, each with a source.

    The hub's `vocabulary.render()` bug that shipped unsourced term lines is the
    reason every line here carries a URL: a vocabulary entry with no source is
    the same High finding as an unsourced fact.
    """
    from .coverage import build_vocabulary

    vocabulary = build_vocabulary(pool)
    by_term: dict[str, Unit] = {}
    for unit in pool.units:
        for token in unit.tokens:
            by_term.setdefault(token, unit)
    ranked = sorted(vocabulary.values(), key=lambda t: (-t.weight, t.term))[:limit]

    lines = [f"# {subject} — vocabulary", "",
             f"> {len(ranked)} terms of the {len(vocabulary)} this corpus uses, ranked by "
             "how distinctive they are within it. Each line names a source that uses "
             "the term.", "", _stamp(report, generated), "",
             "| Term | Units | Sources | Weight | First seen |",
             "|---|---|---|---|---|"]
    for term in ranked:
        witness = by_term.get(term.term)
        where = f"[{witness.heading or witness.document}]({witness.url})" if witness else "—"
        lines.append(f"| {term.term} | {term.frequency} | {term.sources} "
                     f"| {term.weight:.4f} | {where} |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


@dataclass(frozen=True, slots=True)
class Family:
    """The rendered family plus the manifest that describes it."""

    files: Sequence[OutputFile]
    manifest: dict[str, object]

    def get(self, name: str) -> OutputFile:
        for f in self.files:
            if f.path == name:
                return f
        raise KeyError(name)

    @property
    def names(self) -> tuple[str, ...]:
        return tuple(f.path for f in self.files)


def build_family(corpus: Corpus, pool: UnitPool, report: CoverageReport, *,
                 subject: str = "Corpus", generated: str | None = None,
                 small_budget: int = SMALL_TOKEN_BUDGET,
                 layout: dict[str, str] | None = None,
                 with_vocabulary: bool = True) -> Family:
    """Render the whole family and its manifest.

    The manifest is written last, from the rendered bytes, so its numbers are
    measurements rather than predictions — the H8 requirement that a file's
    published token count be *the* token count, not an estimate of one made
    before the file existed.
    """
    stamp = generated or dt.datetime.now(dt.UTC).date().isoformat()
    files = [
        OutputFile("llms.txt", render_index(report, subject=subject, generated=stamp,
                                            layout=layout)),
        OutputFile("llms-full.txt", render_full(corpus, subject=subject, generated=stamp)),
        OutputFile("llms-small.txt", render_small(report, subject=subject, generated=stamp,
                                                  budget=small_budget)),
        OutputFile("llms-facts.txt", render_facts(report, subject=subject, generated=stamp)),
    ]
    if with_vocabulary:
        files.append(OutputFile("llms-vocabulary.txt",
                                render_vocabulary(report, pool, subject=subject,
                                                  generated=stamp)))

    dropped = {}
    for record in corpus.dropped:
        dropped[record.reason] = dropped.get(record.reason, 0) + 1

    manifest: dict[str, object] = {
        "generator": _GENERATOR,
        "generated": stamp,
        "subject": subject,
        "grammar": {"llms-full.txt": FULL_GRAMMAR},
        "files": {f.path: {"bytes": f.bytes, "tokens": f.tokens} for f in files},
        "sections": [{"slug": t.slug, "name": t.name, "units": len(t.units),
                      "sources": len(t.sources), "depth": t.depth}
                     for t in report.topics],
        "coverage": {"comprehensiveness": report.comprehensiveness,
                     "breadth": report.breadth, "depth": report.depth,
                     "unplaced": len(report.unassigned)},
        "counts": {"pages": len(corpus.pages), "units": len(pool.units),
                   "sources": report.sources, "merged_duplicates": pool.merged,
                   **pool.counts()},
        "dropped_empty_pages": dropped.get("empty", 0),
        "dropped": dropped,
        "ladder_ok": True,
    }

    index_tokens = files[0].tokens
    small_tokens = files[2].tokens
    full_tokens = files[1].tokens
    # The ladder must climb. It can fail honestly — a corpus of three sentences
    # has an index as big as its full text — and saying so beats publishing a
    # size ladder that is not one.
    if not (index_tokens <= small_tokens <= full_tokens):
        manifest["ladder_ok"] = False
        manifest["ladder_note"] = (
            f"index {index_tokens} / small {small_tokens} / full {full_tokens} tokens: "
            "the corpus is too small for the ladder to be monotonic"
        )

    files.append(OutputFile("manifest.json", json.dumps(manifest, indent=2,
                                                        sort_keys=False) + "\n"))
    return Family(files=tuple(files), manifest=manifest)


__all__ = [
    "FULL_GRAMMAR",
    "REFERENCE_FIRST",
    "SMALL_TOKEN_BUDGET",
    "Family",
    "build_family",
    "render_facts",
    "render_full",
    "render_index",
    "render_small",
    "render_vocabulary",
]
