#!/usr/bin/env python3
"""
Ollama-to-tinygrad.llm compatibility bridge for NVIDIA eGPU (RTX 5080) on Apple Silicon.
Translates Ollama endpoints (/api/tags, /api/chat, /api/generate, /api/version, /api/ps)
to tinygrad.llm's native OpenAI-compatible server on http://127.0.0.1:8000.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error
from http.server import HTTPServer, BaseHTTPRequestHandler

BACKEND_URL = os.getenv("TINYGRAD_LLM_URL", "http://127.0.0.1:8000")
PORT = int(os.getenv("OLLAMA_PROXY_PORT", "11440"))

class OllamaBridgeHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        # Concise logging
        sys.stderr.write(f"[ollama-egpu] {self.command} {self.path} - {args[0]}\n")

    def _send_json(self, status, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.end_headers()

    def do_HEAD(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

    def do_GET(self):
        if self.path in ("/", ""):
            body = b"Ollama is running"
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        elif self.path == "/api/version":
            return self._send_json(200, {"version": "0.34.4-egpu-rtx5080"})
        elif self.path in ("/api/tags", "/api/ps"):
            try:
                req = urllib.request.Request(f"{BACKEND_URL}/v1/models")
                with urllib.request.urlopen(req, timeout=3) as resp:
                    data = json.loads(resp.read().decode())
                models = []
                for m in data.get("data", []):
                    mid = m.get("id", "tinygrad-model")
                    models.append({
                        "name": mid,
                        "model": mid,
                        "modified_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                        "size": 16000000000,
                        "digest": "rtx5080-hardware-accelerated",
                        "details": {
                            "parent_model": "",
                            "format": "tinygrad-nv",
                            "family": "blackwell",
                            "parameter_size": "16GB-VRAM",
                            "quantization_level": "NVFP4/Q4"
                        }
                    })
                return self._send_json(200, {"models": models})
            except Exception as e:
                return self._send_json(503, {
                    "error": f"tinygrad.llm server not reachable on {BACKEND_URL}: {e}"
                })
        else:
            # Proxy directly to backend if it exists
            return self._proxy_request("GET")

    def do_POST(self):
        content_len = int(self.headers.get("Content-Length", 0))
        post_body = self.rfile.read(content_len) if content_len > 0 else b"{}"
        try:
            req_json = json.loads(post_body.decode())
        except Exception:
            req_json = {}

        if self.path == "/api/chat":
            return self._handle_chat(req_json)
        elif self.path == "/api/generate":
            return self._handle_generate(req_json)
        elif self.path == "/api/show":
            return self._handle_show(req_json)
        elif self.path.startswith("/v1/"):
            return self._proxy_request("POST", post_body)
        else:
            return self._proxy_request("POST", post_body)

    def _handle_show(self, req_json):
        model = req_json.get("model", "Qwen2-beta-14B-Chat")
        return self._send_json(200, {
            "modelfile": f"# Modelfile generated by ollama-egpu\nFROM {model}\nPARAMETER stop <|im_end|>\n",
            "parameters": "stop <|im_end|>",
            "template": "{{ if .System }}<|im_start|>system\n{{ .System }}<|im_end|>\n{{ end }}{{ if .Prompt }}<|im_start|>user\n{{ .Prompt }}<|im_end|>\n{{ end }}<|im_start|>assistant\n",
            "details": {
                "parent_model": "",
                "format": "tinygrad-nv",
                "family": "blackwell",
                "families": ["blackwell", "qwen2"],
                "parameter_size": "14B",
                "quantization_level": "NVFP4/Q4"
            }
        })

    def _handle_chat(self, req_json):
        model = req_json.get("model", "default")
        messages = req_json.get("messages", [])
        stream = req_json.get("stream", True)
        openai_payload = {
            "model": model,
            "messages": messages,
            "stream": stream,
            "temperature": req_json.get("options", {}).get("temperature", 0.0)
        }
        self._forward_to_backend(openai_payload, is_chat=True)

    def _handle_generate(self, req_json):
        model = req_json.get("model", "default")
        prompt = req_json.get("prompt", "")
        stream = req_json.get("stream", True)
        openai_payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "stream": stream,
            "temperature": req_json.get("options", {}).get("temperature", 0.0)
        }
        self._forward_to_backend(openai_payload, is_chat=False)

    def _forward_to_backend(self, openai_payload, is_chat=True):
        req_data = json.dumps(openai_payload).encode("utf-8")
        req = urllib.request.Request(
            f"{BACKEND_URL}/v1/chat/completions",
            data=req_data,
            headers={"Content-Type": "application/json"}
        )
        try:
            resp = urllib.request.urlopen(req, timeout=600)
        except Exception as e:
            return self._send_json(503, {"error": f"Failed to connect to tinygrad backend: {e}"})

        stream = openai_payload.get("stream", True)
        if not stream:
            data = json.loads(resp.read().decode("utf-8"))
            content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
            ollama_resp = {
                "model": openai_payload["model"],
                "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "done": True,
                "total_duration": 1000000000,
                "load_duration": 10000000,
                "prompt_eval_count": data.get("usage", {}).get("prompt_tokens", 0),
                "eval_count": data.get("usage", {}).get("completion_tokens", 0),
            }
            if is_chat:
                ollama_resp["message"] = {"role": "assistant", "content": content}
            else:
                ollama_resp["response"] = content
            return self._send_json(200, ollama_resp)

        self.send_response(200)
        self.send_header("Content-Type", "application/x-ndjson")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

        for line in resp:
            line_str = line.decode("utf-8").strip()
            if not line_str or line_str == "data: [DONE]":
                continue
            if line_str.startswith("data: "):
                try:
                    chunk = json.loads(line_str[6:])
                    delta = chunk.get("choices", [{}])[0].get("delta", {})
                    content = delta.get("content", "")
                    if is_chat:
                        ollama_chunk = {
                            "model": openai_payload["model"],
                            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                            "message": {"role": "assistant", "content": content},
                            "done": False
                        }
                    else:
                        ollama_chunk = {
                            "model": openai_payload["model"],
                            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                            "response": content,
                            "done": False
                        }
                    self.wfile.write((json.dumps(ollama_chunk) + "\n").encode("utf-8"))
                    self.wfile.flush()
                except Exception:
                    pass

        # Final chunk
        final_chunk = {
            "model": openai_payload["model"],
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "done": True
        }
        if is_chat:
            final_chunk["message"] = {"role": "assistant", "content": ""}
        else:
            final_chunk["response"] = ""
        self.wfile.write((json.dumps(final_chunk) + "\n").encode("utf-8"))
        self.wfile.flush()

    def _proxy_request(self, method, body=None):
        url = f"{BACKEND_URL}{self.path}"
        req = urllib.request.Request(url, data=body, method=method)
        for k, v in self.headers.items():
            if k.lower() not in ("host", "content-length"):
                req.add_header(k, v)
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                self.send_response(resp.status)
                for k, v in resp.headers.items():
                    self.send_header(k, v)
                self.end_headers()
                self.wfile.write(resp.read())
        except urllib.error.HTTPError as e:
            self.send_response(e.code)
            self.end_headers()
            self.wfile.write(e.read())
        except Exception as e:
            self._send_json(502, {"error": f"Proxy error: {e}"})

def run():
    server = HTTPServer(("127.0.0.1", PORT), OllamaBridgeHandler)
    print(f"Ollama eGPU bridge listening on http://127.0.0.1:{PORT} -> {BACKEND_URL}")
    server.serve_forever()

if __name__ == "__main__":
    run()
