name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.13
      - name: Run Ruff Linter
        run: |
          uv run --directory hub ruff check .
          uv run --directory api ruff check .
          uv run --directory site ruff check .

  test-api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.13
      - name: Run API Tests
        env:
          EXPLORER_TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres
        run: |
          uv run --directory api --extra test pytest

  test-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.14
      - name: Run Hub Tests
        run: |
          uv run --directory hub pytest

  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Build site
        working-directory: ./site
        run: npm run build
